### ISSUE TITLE
'/node_modules' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by nelszy** [vvo/offline-docs#3]
I'm having trouble with this one... somebody please help... thanks:

$ npm run dev

> offline-docs@1.0.4 dev D:\programming\web development\offline-docs
> npm run server-watch & npm run watch-js & npm run browser-sync

> offline-docs@1.0.4 server-watch D:\programming\web development\offline-docs
> watchy -kw app.js -i '/\.|/node_modules|/test$' -- offline-docs

'/node_modules' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! offline-docs@1.0.4 server-watch: `watchy -kw app.js -i '/\.|/node_modules|/test$' -- offline-docs`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the offline-docs@1.0.4 server-watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nelszy\AppData\Roaming\npm-cache\_logs\2018-02-25T03_40_15_691Z-debug.log

> offline-docs@1.0.4 watch-js D:\programming\web development\offline-docs
> watchify browser.js -o site/bundle.js -dv

path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.dirname (path.js:725:5)
    at Deps.lookupPackage (D:\programming\web development\offline-docs\node_modules\module-deps\index.js:452:29)
    at Deps._transform (D:\programming\web development\offline-docs\node_modules\module-deps\index.js:93:10)
    at Deps.Transform._read (D:\programming\web development\offline-docs\node_modules\readable-stream\lib\_stream_trans                                                                                           form.js:184:10)
    at Deps.Transform._write (D:\programming\web development\offline-docs\node_modules\readable-stream\lib\_stream_tran                                                                                           sform.js:172:12)
    at Labeled.Pipeline._write (D:\programming\web development\offline-docs\node_modules\stream-splicer\index.js:73:22)
    at doWrite (D:\programming\web development\offline-docs\node_modules\readable-stream\lib\_stream_writable.js:279:12                                                                                           )
    at writeOrBuffer (D:\programming\web development\offline-docs\node_modules\readable-stream\lib\_stream_writable.js:                                                                                           266:5)
    at Labeled.Writable.write (D:\programming\web development\offline-docs\node_modules\readable-stream\lib\_stream_wri                                                                                           table.js:211:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! offline-docs@1.0.4 watch-js: `watchify browser.js -o site/bundle.js -dv`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the offline-docs@1.0.4 watch-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nelszy\AppData\Roaming\npm-cache\_logs\2018-02-25T03_40_19_113Z-debug.log

> offline-docs@1.0.4 browser-sync D:\programming\web development\offline-docs
> browser-sync start --proxy 'localhost:5000' --files 'site/**' --no-open

[Browsersync] Proxying: http://
[Browsersync] Access URLs:
 ---------------------------------------------------------
       Local: http://localhost:3000/%27localhost:5000%27
    External: http://192.168.1.5:3000/%27localhost:5000%27
 ---------------------------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.5:3001
 ---------------------------------------------------------
[Browsersync] Watching files...

**Comment by vvo** [comment]
Hi this is a very old module of mine, might be broken so better investigate. What might happen is that it's not compatible with windows shells I guess
